//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.21 at 03:35:18 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://szkolenia.comarch.com/soap/provider/countries")
package com.comarch.szkolenia.soap.provider.countries;
